server:
  port: 8082  

spring:
  cloud:
    gateway:
      routes:
        - id: hotels-service
          uri: http://localhost:8080
          predicates:
            - Path=/api/hotels/**

        - id: users-service
          uri: http://localhost:8081
          predicates:
            - Path=/api/users/**

        - id: bookings-service
          uri: http://localhost:8083
          predicates:
            - Path=/bookings/**

        - id: contacts-service
          uri: http://localhost:8084
          predicates:
            - Path=/contacts/**

      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "http://localhost:4200"
              - "https://hotelbookingbyadinath.netlify.app"
            allowedMethods: "*"
            allowedHeaders: "*"
            allowCredentials: true

      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin

management:
  endpoints:
    web:
      exposure:
        include: "*"
