server:
  port: 8082  

spring:
  cloud:
    gateway:
      routes:
        - id: hotels-service
          uri: https://hotel-service-1m5y.onrender.com
          predicates:
            - Path=/api/hotels/**

        - id: users-service
          uri: https://user-service-kb98.onrender.com
          predicates:
            - Path=/api/users/**

        - id: bookings-service
          uri: https://booking-service-dbej.onrender.com
          predicates:
            - Path=/bookings/**

        - id: contacts-service
          uri: https://contact-service-lzsl.onrender.com
          predicates:
            - Path=/contacts/**

      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "http://localhost:4200"
              - "https://hotelbookingbyadinath.netlify.app"
            allowedMethods: "*"
            allowedHeaders: "*"
            allowCredentials: true

      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin

management:
  endpoints:
    web:
      exposure:
        include: "*"
