server:
  port: 8082  

spring:
  cloud:
    gateway:
      routes:
        - id: hotels-service
          uri: https://hotel-service-1m5y.onrender.com
          predicates:
            - Path=/api/hotels/**
          filters:
            - RewritePath=/api/hotels/(?<segment>.*), /${segment}

        - id: users-service
          uri: https://user-service-kb98.onrender.com
          predicates:
            - Path=/api/users/**
          filters:
            - RewritePath=/api/users/(?<segment>.*), /${segment}

        - id: bookings-service
          uri: https://booking-service-dbej.onrender.com
          predicates:
            - Path=/api/bookings/**
          filters:
            - RewritePath=/api/bookings/(?<segment>.*), /${segment}

        - id: contacts-service
          uri: https://contact-service-lzsl.onrender.com
          predicates:
            - Path=/api/contacts/**
          filters:
            - RewritePath=/api/contacts/(?<segment>.*), /${segment}

      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "http://localhost:4200"
              - "https://hotelbookingbyadinath.netlify.app"
            allowedMethods: "*"
            allowedHeaders: "*"
            allowCredentials: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
